"""create document_pipeline_state table

Revision ID: 1f804e6d4e00
Revises: 2b364601c885
Create Date: 2026-09-12 13:05:11.898648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f804e6d4e00'
down_revision: Union[str, Sequence[str], None] = '2b364601c885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_pipeline_state',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('clean', 'needs_review', name='document_status'), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('canonical_invoice_id', sa.UUID(), nullable=True),
    sa.Column('counterparty_id', sa.UUID(), nullable=True),
    sa.Column('counterparty_match_strategy', sa.Enum('vat_exact', 'iban_exact', 'fuzzy_name', 'new', name='match_strategy'), nullable=True),
    sa.Column('counterparty_match_confidence', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_invoice_id'], ['canonical_invoice.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_pipeline_state')
    # ### end Alembic commands ###
    # manually added: drop_table does not drop the Postgres ENUM types it depends on
    sa.Enum(name='match_strategy').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='document_status').drop(op.get_bind(), checkfirst=True)
