"""create counterparty and counterparty_alias tables

Revision ID: 2b364601c885
Revises: b9322e7c562c
Create Date: 2026-09-12 13:00:22.092945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b364601c885'
down_revision: Union[str, Sequence[str], None] = 'b9322e7c562c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparty',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('unconfirmed', 'confirmed', name='counterparty_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparty_tenant_id'), 'counterparty', ['tenant_id'], unique=False)
    op.create_table('counterparty_alias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('alias_type', sa.Enum('name', 'vat_number', 'iban', name='alias_type'), nullable=False),
    sa.Column('raw_value', sa.String(), nullable=False),
    sa.Column('normalized_value', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'alias_type', 'normalized_value', name='uq_counterparty_alias_tenant_type_value')
    )
    op.create_index(op.f('ix_counterparty_alias_counterparty_id'), 'counterparty_alias', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_counterparty_alias_normalized_value'), 'counterparty_alias', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_counterparty_alias_tenant_id'), 'counterparty_alias', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counterparty_alias_tenant_id'), table_name='counterparty_alias')
    op.drop_index(op.f('ix_counterparty_alias_normalized_value'), table_name='counterparty_alias')
    op.drop_index(op.f('ix_counterparty_alias_counterparty_id'), table_name='counterparty_alias')
    op.drop_table('counterparty_alias')
    op.drop_index(op.f('ix_counterparty_tenant_id'), table_name='counterparty')
    op.drop_table('counterparty')
    # ### end Alembic commands ###
    # manually added: drop_table does not drop the Postgres ENUM types it depends on
    sa.Enum(name='alias_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='counterparty_status').drop(op.get_bind(), checkfirst=True)
