"""create source_document table

Revision ID: 642143b4db5f
Revises: 
Create Date: 2026-09-12 12:48:06.176115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642143b4db5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('blob_key', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('peppol', 'email', 'upload', 'mobile', name='channel'), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingest_status', sa.Enum('received', name='ingest_status'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sha256', name='uq_source_document_tenant_sha256')
    )
    op.create_index(op.f('ix_source_document_tenant_id'), 'source_document', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_document_tenant_id'), table_name='source_document')
    op.drop_table('source_document')
    # ### end Alembic commands ###
    # manually added: drop_table does not drop the Postgres ENUM types it depends on
    sa.Enum(name='ingest_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='channel').drop(op.get_bind(), checkfirst=True)
