"""create canonical_invoice table

Revision ID: 8305f19748b1
Revises: 642143b4db5f
Create Date: 2026-09-12 12:53:30.787139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8305f19748b1'
down_revision: Union[str, Sequence[str], None] = '642143b4db5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_invoice',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('extractor_name', sa.String(), nullable=False),
    sa.Column('extractor_version', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version', name='uq_canonical_invoice_document_version')
    )
    op.create_index(op.f('ix_canonical_invoice_document_id'), 'canonical_invoice', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canonical_invoice_document_id'), table_name='canonical_invoice')
    op.drop_table('canonical_invoice')
    # ### end Alembic commands ###
