"""create validation_run and validation_result tables

Revision ID: b9322e7c562c
Revises: 8305f19748b1
Create Date: 2026-09-12 12:58:02.441223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9322e7c562c'
down_revision: Union[str, Sequence[str], None] = '8305f19748b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('canonical_invoice_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_invoice_id'], ['canonical_invoice.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_run_document_id'), 'validation_run', ['document_id'], unique=False)
    op.create_table('validation_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Enum('vat_rate_arithmetic_mismatch', 'vat_breakdown_total_mismatch', 'line_net_total_mismatch', 'totals_gross_mismatch', 'supplier_vat_structurally_invalid', 'supplier_vat_vies_invalid', 'vies_unavailable', 'supplier_iban_checksum_invalid', 'invoice_date_in_future', 'invoice_date_too_old', 'buyer_vat_mismatch', 'currency_not_eur', 'duplicate_invoice', 'near_duplicate_invoice', name='validation_code'), nullable=False),
    sa.Column('severity', sa.Enum('error', 'warning', name='validation_severity'), nullable=False),
    sa.Column('message_nl', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['validation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_result_run_id'), 'validation_result', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_result_run_id'), table_name='validation_result')
    op.drop_table('validation_result')
    op.drop_index(op.f('ix_validation_run_document_id'), table_name='validation_run')
    op.drop_table('validation_run')
    # ### end Alembic commands ###
    # manually added: drop_table does not drop the Postgres ENUM types it depends on
    sa.Enum(name='validation_code').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='validation_severity').drop(op.get_bind(), checkfirst=True)
